name:                httprobe
version:             "2.0"
synopsis:            Simple HTTP probe, that will acknowledge everything and print it to stdout
homepage:            https://github.com/tr00per/httprobe/blob/master/README.md
author:              Artur Czajka
maintainer:          arturczajka@gmail.com
copyright:           2016-2018 Artur Czajka
category:            Web

dependencies:
    - base

library:
    exposed-modules:
        - Network.HTTP.Probe
    source-dirs: src
    dependencies:
        - mtl
        - http-types
        - bytestring
        - text
        - aeson
        - extra
        - case-insensitive
        - servant-server
        - wai
        - warp
        - random

executables:
    httprobe:
        ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
        source-dirs: app
        main: Main.hs
        dependencies:
            - httprobe
